---
title: "reddit text analysis"
author: "Laura Fontanills"
date: "2022-12-14"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Required packages

```{r}
library(tidyverse) # data cleaning
library(tidytext) #NLP toolkit
```

### Data sources

Same as reddit-science-analysis (possibly copy here later?)

### Text wrangling

Subset dataframes with titles, flair, domain

```{r, subset dataframes}
# subset dataframes with title text, flair, domain

text_month <- top_month[,c("month_rank","id", "flair", "domain", "post_title")]
text_year <- top_year[,c("year_rank","id", "flair", "domain", "post_title")]
text_all <- top_all[,c("all_time_rank","id", "flair", "domain", "post_title")]

```

To work with titles as a tidy dataset, restructure to one token per row
```{r}
# restructure one token per row: unnesttokens
tidy_month <-text_month %>% 
  unnest_tokens(word, post_title)
tidy_month

tidy_year <- text_year %>% 
  unnest_tokens(word, post_title)
tidy_year

tidy_all <- text_all %>% 
  unnest_tokens(word, post_title)
tidy_all
```

